In [1]:
import numpy as np

In [3]:
a=np.array([3,4,5,6,7,8])
max(a)


8

In [4]:
min(a)

3

In [6]:
sum(a)

33

In [8]:
b=np.random.randint(3,9,(3,4))
print(b)

[[3 5 8 7]
 [3 5 3 8]
 [6 4 3 4]]


In [10]:
print(b.max(axis=0))#0 for column wise 

[6 5 8 8]


In [11]:
print(b.max(axis=1))#1 for row wise

[8 8 6]


In [12]:
print(max(b.max(axis=1)))

8
