In [1]:
import numpy as np

In [10]:
a=np.random.randint(3,50,50)
print(a)

[49 30 35 24 31 31 11 49 18 32 48 21 19 36  8  3 27 44 40 34 17 41 38 36
 46 36 11 31 22  8 27 15 49 37 23 49 37 21  7 14 38 44 43 42 39 19 39 21
 36  9]


In [11]:
sorted_a=np.sort(a)

In [12]:
sorted_a

array([ 3,  7,  8,  8,  9, 11, 11, 14, 15, 17, 18, 19, 19, 21, 21, 21, 22,
       23, 24, 27, 27, 30, 31, 31, 31, 32, 34, 35, 36, 36, 36, 36, 37, 37,
       38, 38, 39, 39, 40, 41, 42, 43, 44, 44, 46, 48, 49, 49, 49, 49])

In [13]:
b=np.random.randint(3,50,(5,6))
print(b)

[[33 15 39 24 45 29]
 [36 28 36  5  4 40]
 [19 45 40 17 28 24]
 [25 11 14 44 13 39]
 [44 16 27 44 26 24]]


In [16]:
print(np.reshape(np.sort(b.flatten(),kind='mergesort'),(5,6)))

[[ 4  5 11 13 14 15]
 [16 17 19 24 24 24]
 [25 26 27 28 28 29]
 [33 36 36 39 39 40]
 [40 44 44 44 45 45]]
