In [1]:
import numpy as np

In [2]:
a=np.random.randint(3,9,(3,4))
print(a)

[[3 3 7 3]
 [8 5 4 4]
 [7 8 3 7]]


In [4]:
a=a+1
print(a)

[[4 4 8 4]
 [9 6 5 5]
 [8 9 4 8]]


In [5]:
a=a-1
print(a)

[[3 3 7 3]
 [8 5 4 4]
 [7 8 3 7]]


In [6]:
a=a*3
print(a)

[[ 9  9 21  9]
 [24 15 12 12]
 [21 24  9 21]]


In [7]:
a=a/3
print(a)

[[3. 3. 7. 3.]
 [8. 5. 4. 4.]
 [7. 8. 3. 7.]]
