In [1]:
import numpy as np

In [2]:
a=np.random.randint(3,9,(3,3))
b=np.random.randint(4,9,(3,3))

In [4]:
a

array([[3, 3, 8],
       [3, 8, 5],
       [5, 4, 4]])

In [5]:
b

array([[5, 5, 7],
       [5, 7, 5],
       [6, 5, 7]])

In [3]:
print(a.dot(b))

[[78 76 92]
 [85 96 96]
 [69 73 83]]
