In [1]:
import numpy as np

In [2]:
a=np.random.randint(3,9,(3,4))
b=np.random.randint(3,9,(3,4))

In [3]:
a

array([[8, 4, 6, 3],
       [8, 4, 4, 8],
       [7, 5, 7, 4]])

In [4]:
b

array([[4, 8, 7, 4],
       [3, 3, 5, 6],
       [8, 4, 8, 7]])

In [6]:
np.concatenate((a,b),axis=0) 

array([[8, 4, 6, 3],
       [8, 4, 4, 8],
       [7, 5, 7, 4],
       [4, 8, 7, 4],
       [3, 3, 5, 6],
       [8, 4, 8, 7]])

In [7]:
np.concatenate((a,b),axis=1) 

array([[8, 4, 6, 3, 4, 8, 7, 4],
       [8, 4, 4, 8, 3, 3, 5, 6],
       [7, 5, 7, 4, 8, 4, 8, 7]])

In [9]:
np.hstack((a,b))

array([[8, 4, 6, 3, 4, 8, 7, 4],
       [8, 4, 4, 8, 3, 3, 5, 6],
       [7, 5, 7, 4, 8, 4, 8, 7]])

In [10]:
np.vstack((a,b))

array([[8, 4, 6, 3],
       [8, 4, 4, 8],
       [7, 5, 7, 4],
       [4, 8, 7, 4],
       [3, 3, 5, 6],
       [8, 4, 8, 7]])