In [1]:
import numpy as np

In [8]:
a=np.random.randint(1,9,(4,4))
a

array([[4, 4, 1, 4],
       [5, 7, 7, 7],
       [8, 6, 2, 6],
       [3, 2, 2, 5]])

In [9]:
np.hsplit(a,2)

[array([[4, 4],
        [5, 7],
        [8, 6],
        [3, 2]]),
 array([[1, 4],
        [7, 7],
        [2, 6],
        [2, 5]])]

In [10]:
np.vsplit(a,2)

[array([[4, 4, 1, 4],
        [5, 7, 7, 7]]),
 array([[8, 6, 2, 6],
        [3, 2, 2, 5]])]