In [1]:
import numpy as np

In [3]:
a=np.array([[[4,5],[6,7],[8,9]]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[[[4 5]
  [6 7]
  [8 9]]]
3
(1, 3, 2)
6
int32


In [6]:
b=np.array([3,4,5,6,7])
print(b)
c=np.array(b,ndmin=4)
print(c)
print(c.ndim)
print(c.shape)

[3 4 5 6 7]
[[[[3 4 5 6 7]]]]
4
(1, 1, 1, 5)
