In [1]:
import numpy as np

In [4]:
a=np.random.randint(3,9,(3,4))
print(a)
print(a.shape)

[[6 8 8 7]
 [7 4 7 6]
 [6 3 4 4]]
(3, 4)


In [8]:
a=a.reshape(4,3)
print(a)
print(a.shape)

[[6 8 8]
 [7 7 4]
 [7 6 6]
 [3 4 4]]
(4, 3)


In [9]:
a=a.reshape(2,6)
print(a)
print(a.shape)

[[6 8 8 7 7 4]
 [7 6 6 3 4 4]]
(2, 6)
